# Quality gates for all changes to main
# - Runs on PRs to main
# - Ensures code quality (lint)
# - Runs tests
# - Verifies build (checks deployability)
name: Pull Request Checks
on:
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  quality-checks:
    runs-on: ubuntu-latest
    steps:
      - run: exit 1
