# Creates GitHub releases after version bumps
# - Runs when version bump PRs are merged
# - Creates a GitHub release with the new version
# - Only processes PRs from version-bump branches
name: Create Release
on:
  pull_request:
    types: [closed]
    branches: [test/fake-main]
  workflow_dispatch:

jobs:
  create-release:
    if: |
      github.event.pull_request.merged == true &&
      startsWith(github.event.pull_request.head.ref, 'version-bump/')
    runs-on: ubuntu-latest
    permissions:
      contents: write # Needed for creating releases
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_PAT }} # Same PAT as version-bump workflow

      - name: Get version from package.json
        id: version
        run: |
          VERSION=$(node -p "require('./package.json').version")
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ steps.version.outputs.version }}
          name: v${{ steps.version.outputs.version }}
          generate_release_notes: true
          prerelease: ${{ contains(steps.version.outputs.version, '-') }}
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }} # Same PAT for release creation
