# Creates GitHub releases after version bumps
# - Runs when version bump PRs are merged
# - Creates a GitHub release with the new version
# - Only processes PRs from version-bump branches
name: Create Release
on:
  pull_request:
    types: [closed]
    branches: [main]
  workflow_dispatch:

jobs:
  create-release:
    if: |
      github.event.pull_request.merged == true &&
      startsWith(github.event.pull_request.head.ref, 'version-bump/')
    runs-on: ubuntu-latest
    steps:
      - run: exit 1
