# Creates PRs for version updates
# - Triggered manually with version type
# - Updates package.json version
# - Creates PR for the version bump
name: Version Bump
on:
  workflow_dispatch:
    inputs:
      version_type:
        description: 'Version type (patch, minor, major)'
        required: true
        default: 'patch'
        type: choice
        options: [patch, minor, major]

jobs:
  create-version-pr:
    runs-on: ubuntu-latest
    steps:
      - run: exit 1
