name: Version Bump
on:
  workflow_dispatch:
    inputs:
      version_type:
        description: 'Version type (patch, minor, major)'
        required: true
        default: 'patch'
        type: choice
        options:
          - patch
          - minor
          - major

jobs:
  create-version-pr:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Git
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Create version bump branch
        run: |
          branch_name="version-bump/$(date +%Y%m%d-%H%M%S)"
          git checkout -b $branch_name
          NEW_VERSION=$(npm version ${{ inputs.version_type }} --no-git-tag-version)
          echo "NEW_VERSION=${NEW_VERSION#v}" >> $GITHUB_ENV
          echo "branch_name=$branch_name" >> $GITHUB_ENV
          git add package*.json
          git commit -m "Bump version to $NEW_VERSION"
          git push origin $branch_name

      - name: Create Pull Request
        # Release-As directive tells GitHub to create a version tag when the PR is merged
        run: |
          gh pr create \
            --title "chore: bump version to ${{ env.NEW_VERSION }}" \
            --body "Automated version bump to ${{ env.NEW_VERSION }}.

            Release-As: ${{ env.NEW_VERSION }}" \
            --base main \
            --head ${{ env.branch_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
